############# Database Properties ###########################################
spring:
  datasource:
    url: "jdbc:${env.SPRING_DATASOURCE_DRIVER}://${env.SPRING_DATASOURCE_HOST}:${env.SPRING_DATASOURCE_PORT}/${env.SPRING_DATASOURCE_DATABASE}"
    username: ${env.SPRING_DATASOURCE_USERNAME}
    password: ${env.SPRING_DATASOURCE_PASSWORD}
    driver: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

############# Jwt Properties ###########################################
jwt:
  service:
    secret-key: ${env.JWT_SERVICE_SECRET-KEY}
